services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./.env
    environment:
      # Pass the backend URL as an environment variable
      REACT_APP_BACKEND_API_URL: ${BACKEND_API_URL}  # Use the project-level variable
    networks:
      - app-network
    depends_on:
      - backend
  db:
    image: postgres:13-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge