services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/logs:/usr/src/app/logs
      - ./common:/usr/src/common
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - ./common:/usr/src/common  # Mount the common folder
    env_file:
      - ./.env
    environment:
      REACT_APP_BACKEND_API_URL: ${BACKEND_API_URL}
    networks:
      - app-network
    depends_on:
      - backend
    command: /bin/sh -c "[ ! -L /usr/src/app/src/common ] && ln -s /usr/src/common /usr/src/app/src/common || true && npm install && npm start"

  db:
    image: postgres:13-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data  # Volume for persisting data
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
